### ISSUE TITLE
Error: Invariant: headers() expects to have requestAsyncStorage, none available.

### ISSUE THREAD

**Issue by happyrw** [AntonioErdeljac/next-auth-v5-advanced-guide#24]
When I try to login using providers[Google, Github] I get this error message. Where am I going to check?

Error: Invariant: headers() expects to have requestAsyncStorage, none available.
    at headers (headers.js:42:15)
    at signIn (actions.js:6:44)
    at signIn (index.js:134:26)
    at socialLogin (login-form.tsx:62:25)
    at onClick (login-form.tsx:111:127)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20498:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20547:16)
    at invokeGuardedCallback (react-dom.development.js:20622:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20636:25)
    at executeDispatch (react-dom.development.js:31986:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32018:7)
    at processDispatchQueue (react-dom.development.js:32031:5)
    at dispatchEventsForPlugins (react-dom.development.js:32042:3)
    at eval (react-dom.development.js:32232:12)
    at batchedUpdates$1 (react-dom.development.js:24843:12)
    at batchedUpdates (react-dom.development.js:28703:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32231:3)
    at dispatchEvent (react-dom.development.js:29999:5)
    at dispatchDiscreteEvent (react-dom.development.js:29970:5)

**Comment by AdylshaY** [comment]
If you importing like this, `import { signIn } from '@/auth';` this is for server components. For the client components you need to import `import { signIn } from 'next-auth/react';` like this.

**Comment by happyrw** [comment]
Thank you Mr @AdylshaY I get the point

**Comment by happyrw** [comment]
How to resolve this 


[12:09:07.643] Running build in Washington, D.C., USA (East) – iad1
[12:09:07.922] Retrieving list of deployment files...
[12:09:08.433] Downloading 70 deployment files...
[12:09:08.516] Previous build caches not available
[12:09:09.250] Running "vercel build"
[12:09:09.744] Vercel CLI 33.5.1
[12:09:10.086] Installing dependencies...
[12:09:11.706] npm ERR! code ERESOLVE
[12:09:11.709] npm ERR! ERESOLVE could not resolve
[12:09:11.709] npm ERR! 
[12:09:11.709] npm ERR! While resolving: @next-auth/prisma-adapter@1.0.7
[12:09:11.709] npm ERR! Found: next-auth@5.0.0-beta.5
[12:09:11.710] npm ERR! node_modules/next-auth
[12:09:11.710] npm ERR!   next-auth@"^5.0.0-beta.5" from the root project
[12:09:11.710] npm ERR! 
[12:09:11.710] npm ERR! Could not resolve dependency:
[12:09:11.710] npm ERR! peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.7
[12:09:11.710] npm ERR! node_modules/@next-auth/prisma-adapter
[12:09:11.710] npm ERR!   @next-auth/prisma-adapter@"^1.0.7" from the root project
[12:09:11.710] npm ERR! 
[12:09:11.710] npm ERR! Conflicting peer dependency: next-auth@4.24.6
[12:09:11.710] npm ERR! node_modules/next-auth
[12:09:11.710] npm ERR!   peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.7
[12:09:11.711] npm ERR!   node_modules/@next-auth/prisma-adapter
[12:09:11.711] npm ERR!     @next-auth/prisma-adapter@"^1.0.7" from the root project
[12:09:11.711] npm ERR! 
[12:09:11.711] npm ERR! Fix the upstream dependency conflict, or retry
[12:09:11.711] npm ERR! this command with --force or --legacy-peer-deps
[12:09:11.711] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[12:09:11.711] npm ERR! 
[12:09:11.711] npm ERR! 
[12:09:11.711] npm ERR! For a full report see:
[12:09:11.711] npm ERR! /vercel/.npm/_logs/2024-02-19T10_09_10_429Z-eresolve-report.txt
[12:09:11.712] 
[12:09:11.712] npm ERR! A complete log of this run can be found in: /vercel/.npm/_logs/2024-02-19T10_09_10_429Z-debug-0.log
[12:09:11.724] Error: Command "npm install" exited with 1
[12:09:12.185]  ?

Mr @AdylshaY @AntonioErdeljac

**Comment by AdylshaY** [comment]
I think your package versions is incorrect. My versions is: 
    "@auth/prisma-adapter": "^1.4.0"
    "next-auth": "^5.0.0-beta.11"

Can you try with these versions?

**Comment by happyrw** [comment]
Let me try with this I will let you know
Thanks
________________________________

**Comment by happyrw** [comment]
Again I get this

[12:48:43.021] Running build in Washington, D.C., USA (East) – iad1
[12:48:43.131] Retrieving list of deployment files...
[12:48:43.662] Downloading 70 deployment files...
[12:48:43.769] Previous build caches not available
[12:48:44.206] Running "vercel build"
[12:48:44.694] Vercel CLI 33.5.1
[12:48:45.053] Installing dependencies...
[12:48:46.690] npm ERR! code ERESOLVE
[12:48:46.692] npm ERR! ERESOLVE could not resolve
[12:48:46.693] npm ERR!
[12:48:46.693] npm ERR! While resolving: @***@***.***
[12:48:46.693] npm ERR! Found: ***@***.***
[12:48:46.693] npm ERR! node_modules/next-auth
[12:48:46.693] npm ERR!   next-auth@"^5.0.0-beta.11" from the root project
[12:48:46.693] npm ERR!
[12:48:46.693] npm ERR! Could not resolve dependency:
[12:48:46.693] npm ERR! peer next-auth@"^4" from @***@***.***
[12:48:46.693] npm ERR! ***@***.***/prisma-adapter
[12:48:46.693] npm ERR!   @next-auth/prisma-adapter@"^1.0.7" from the root project
[12:48:46.693] npm ERR!
[12:48:46.693] npm ERR! Conflicting peer dependency: ***@***.***
[12:48:46.693] npm ERR! node_modules/next-auth
[12:48:46.694] npm ERR!   peer next-auth@"^4" from @***@***.***
[12:48:46.694] npm ERR!   ***@***.***/prisma-adapter
[12:48:46.694] npm ERR!     @next-auth/prisma-adapter@"^1.0.7" from the root project
[12:48:46.694] npm ERR!
[12:48:46.694] npm ERR! Fix the upstream dependency conflict, or retry
[12:48:46.694] npm ERR! this command with --force or --legacy-peer-deps
[12:48:46.694] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[12:48:46.694] npm ERR!
[12:48:46.694] npm ERR!
[12:48:46.694] npm ERR! For a full report see:
[12:48:46.694] npm ERR! /vercel/.npm/_logs/2024-02-19T10_48_45_401Z-eresolve-report.txt
[12:48:46.695]
[12:48:46.695] npm ERR! A complete log of this run can be found in: /vercel/.npm/_logs/2024-02-19T10_48_45_401Z-debug-0.log
[12:48:46.707] Error: Command "npm install" exited with 1
[12:48:46.932]

package.json file

{
  "name": "auth_tutorial",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "prisma generate"
  },
  "dependencies": {
    ***@***.***/prisma-adapter": "^1.4.0",
    ***@***.***/resolvers": "^3.3.4",
    ***@***.***/prisma-adapter": "^1.0.7",
    ***@***.***/client": "^5.9.1",
    "bcrypt": "^5.1.1",
    "bcryptjs": "^2.4.3",
    "next": "^14.1.0",
    "next-auth": "^5.0.0-beta.11",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.50.0",
    "react-icons": "^5.0.1",
    "react-spinners": "^0.13.8",
    "react-toastify": "^10.0.4",
    "resend": "^3.1.0",
    "uuid": "^9.0.1",
    "yup": "^1.3.3"
  },
  "devDependencies": {
    ***@***.***/bcryptjs": "^2.4.6",
    ***@***.***/node": "^20",
    ***@***.***/react": "^18",
    ***@***.***/react-dom": "^18",
    ***@***.***/uuid": "^9.0.8",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "postcss": "^8",
    "prisma": "^5.9.1",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}


________________________________

**Comment by AdylshaY** [comment]
***@***.***/prisma-adapter": "^1.4.0",
    ***@***.***/prisma-adapter": "^1.0.7",

You have these, can you delete second (1.0.7) and try again?

**Comment by happyrw** [comment]
[16:18:35.431] Running build in Washington, D.C., USA (East) – iad1
[16:18:35.521] Retrieving list of deployment files...
[16:18:36.026] Downloading 70 deployment files...
[16:18:36.243] Previous build caches not available
[16:18:36.551] Running "vercel build"
[16:18:39.633] Vercel CLI 33.5.1
[16:18:40.285] Installing dependencies...
[16:18:55.670]
[16:18:55.670] > ***@***.*** postinstall
[16:18:55.670] > prisma generate
[16:18:55.670]
[16:18:56.418] Environment variables loaded from .env
[16:18:56.420] Prisma schema loaded from prisma/schema.prisma
[16:18:56.892]
[16:18:56.892] ✔ Generated Prisma Client (v5.9.1) to
.***@***.***/client in 76ms
[16:18:56.893]
[16:18:56.893] Start using Prisma Client in Node.js (See:
https://pris.ly/d/client)
[16:18:56.893] ```
[16:18:56.893] import { PrismaClient } from ***@***.***/client'
[16:18:56.893] const prisma = new PrismaClient()
[16:18:56.893] ```
[16:18:56.893] or start using Prisma Client at the edge (See:
https://pris.ly/d/accelerate)
[16:18:56.893] ```
[16:18:56.893] import { PrismaClient } from ***@***.***/client/edge'
[16:18:56.893] const prisma = new PrismaClient()
[16:18:56.893] ```
[16:18:56.893]
[16:18:56.893] See other ways of importing Prisma Client:
http://pris.ly/d/importing-client
[16:18:56.893]
[16:18:56.893]
┌─────────────────────────────────────────────────────────────┐
[16:18:56.893] │  Deploying your app to serverless or edge functions?
 │
[16:18:56.893] │  Try Prisma Accelerate for connection pooling and caching.
 │
[16:18:56.893] │  https://pris.ly/cli/accelerate
  │
[16:18:56.893]
└─────────────────────────────────────────────────────────────┘
[16:18:56.893]
[16:18:56.931]
[16:18:56.932] added 459 packages in 16s
[16:18:56.932]
[16:18:56.932] 149 packages are looking for funding
[16:18:56.932]   run `npm fund` for details
[16:18:56.967] Detected Next.js version: 14.1.0
[16:18:56.971] Detected `package-lock.json` generated by npm 7+
[16:18:56.971] Running "npm run build"
[16:18:57.397]
[16:18:57.398] > ***@***.*** build
[16:18:57.398] > next build
[16:18:57.398]
[16:18:57.986] Attention: Next.js now collects completely anonymous
telemetry regarding usage.
[16:18:57.986] This information is used to shape Next.js' roadmap and
prioritize features.
[16:18:57.986] You can learn more, including how to opt-out if you'd not
like to participate in this anonymous program, by visiting the following
URL:
[16:18:57.987] https://nextjs.org/telemetry
[16:18:57.987]
[16:18:58.086]    ▲ Next.js 14.1.0
[16:18:58.086]    - Environments: .env
[16:18:58.086]
[16:18:58.163]    Creating an optimized production build ...
[16:19:12.327] Failed to compile.
[16:19:12.327]
[16:19:12.327] ./auth.ts
[16:19:12.327] Module not found: Can't resolve ***@***.***/prisma-adapter'
[16:19:12.327]
[16:19:12.327] https://nextjs.org/docs/messages/module-not-found
[16:19:12.327]
[16:19:12.327] Import trace for requested module:
[16:19:12.328] ./actions/logout.ts
[16:19:12.328]
./node_modules/next/dist/build/webpack/loaders/next-flight-action-entry-loader.js?actions=%5B%5B%22%2Fvercel%2Fpath0%2Factions%2Flogout.ts%22%2C%5B%22logOut%22%5D%5D%2C%5B%22%2Fvercel%2Fpath0%2Factions%2Fadmin.ts%22%2C%5B%22admin%22%5D%5D%5D&__client_imported__=true!
[16:19:12.328]
[16:19:12.328] ./auth.ts
[16:19:12.328] Module not found: Can't resolve ***@***.***/prisma-adapter'
[16:19:12.328]
[16:19:12.328] https://nextjs.org/docs/messages/module-not-found
[16:19:12.328]
[16:19:12.328] Import trace for requested module:
[16:19:12.328] ./app/api/auth/[...nextauth]/route.ts
[16:19:12.328]
[16:19:12.328]
[16:19:12.328] > Build failed because of webpack errors
[16:19:12.386] Error: Command "npm run build" exited with 1
[16:19:12.723]

An other error [ Jesus  ! ]
